telegram_token: 'YOUR_TELEGRAM_BOT_TOKEN'
openai_api_key: 'YOUR_OPENAI_API_KEY'
habits:
  sleep:
    type: integer
    description: "Number of hours you slept."
  exercise:
    type: boolean
    description: "Whether you exercised today."
  mood:
    type:
      - integer
      - "null"
    minimum: 1
    maximum: 5
    description: "Your mood level from 1 (bad) to 5 (good). Use 'null' if not specified."
  diary:
    type: string
    description: "A brief summary of your day with correct grammar."
reminder_time: '17:15'  # 24-hour format
data_directory: 'data/habits/'