version: '3.8'
services:
  telegram_bot:
    image: tg_bot_habits:v1.0
    environment:
      - TELEGRAM_TOKEN=TELEGRAM_TOKEN
      - OPENAI_API_KEY=OPENAI_API_KEY
      - GOOGLE_CREDENTIALS=google_service_account_credentials.json
    volumes:
      - /path/to/local/google_service_account_credentials.json:google_service_account_credentials.json
